"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production
SECRET_KEY = config('SECRET_KEY', default='django-insecure-ss_8^n9y&2l67iwpc&tfxcd1qn-y%yiiv2dejrgp8ym^rx-&hf')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'newapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'newapp.context_processors.admin_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Using SQLite for development (temporary)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Using SQLite for development (temporary). This makes local setup easier
# and avoids requiring a working MS SQL server while developing.
"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

 #MS SQL Server Configuration (keep for production / MS SQL use):
"""DATABASES = {
     'default': {
         'ENGINE': 'mssql',
         'NAME': 'CRM',  # Your database name
         'USER': '',  # Leave empty for Windows Authentication
         'PASSWORD': '',  # Leave empty for Windows Authentication
         'HOST': 'MANUSHARMA',  # Your SQL Server name
         'PORT': '',
         'OPTIONS': {
             'driver': 'ODBC Driver 18 for SQL Server',
             'extra_params': 'Trusted_Connection=yes;TrustServerCertificate=yes;',
         },
     }
}"""
import os

DATABASES = {
    'default': {
        'ENGINE': 'mssql',

        # SAME DB name as database.py
        'NAME': os.environ.get('MSSQL_DB', 'crm_database'),

        # Use SQL auth only if provided
        'USER': os.environ.get('MSSQL_USER', ''),
        'PASSWORD': os.environ.get('MSSQL_PASSWORD', ''),

        # SAME server as database.py
        'HOST': os.environ.get('MSSQL_SERVER', 'DESKTOP-47SJR24'),

        'PORT': '',

        'OPTIONS': {
            # SAME / compatible driver
            'driver': os.environ.get(
                'MSSQL_DRIVER',
                'ODBC Driver 17 for SQL Server'
            ),

            # Windows Auth support
            'extra_params': 'Trusted_Connection=yes;TrustServerCertificate=yes;',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    # Project-level static folder (repo root static/)
    BASE_DIR.parent / "static",
]


# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication URLs
LOGIN_URL = 'newapp:signin'
LOGIN_REDIRECT_URL = 'newapp:dashboard'
LOGOUT_REDIRECT_URL = 'newapp:index'


# ==============================
# AUTO LOGOUT AFTER INACTIVITY
# ==============================

# Logout user after 10 minutes (600 seconds) of inactivity
SESSION_COOKIE_AGE = 600  # 10 minutes

# Reset session timer on every request
SESSION_SAVE_EVERY_REQUEST = True

# Expire session when browser is closed (optional but professional)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
