# Generated by Django 5.2.4 on 2025-11-01 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('SALES_REP', 'Sales Representative'), ('SALES_HEAD', 'Sales Head'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='SALES_REP', max_length=20)),
                ('region', models.CharField(blank=True, choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West'), ('CENTRAL', 'Central')], max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='newapp.salesemployee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Employee',
                'verbose_name_plural': 'Sales Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CUSTOMER', 'Customer'), ('LEAD', 'Lead')], default='PROSPECT', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal Sent'), ('NEGOTIATION', 'In Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('INACTIVE', 'Inactive')], default='NEW', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prospects', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='newapp.salesemployee')),
            ],
            options={
                'verbose_name': 'Prospect/Customer',
                'verbose_name_plural': 'Prospects/Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_time', models.TimeField(default=django.utils.timezone.now)),
                ('meeting_agenda', models.TextField()),
                ('meeting_outcome', models.TextField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative'), ('DEAL_CLOSED', 'Deal Closed'), ('FOLLOW_UP', 'Follow-up Required')], max_length=20, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('visiting_card', models.ImageField(blank=True, null=True, upload_to='visit_attachments/cards/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visit_attachments/photos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='visit_attachments/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visits', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='newapp.prospectcustomer')),
                ('sales_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='newapp.salesemployee')),
            ],
            options={
                'verbose_name': 'Visit Log',
                'verbose_name_plural': 'Visit Logs',
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
    ]
