# Generated by Django 5.2.7 on 2025-11-04 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_department_alter_salesemployee_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('lead_source', models.CharField(choices=[('VISIT', 'Visit'), ('REFERENCE', 'Reference'), ('WEB', 'Website'), ('CAMPAIGN', 'Campaign'), ('COLD_CALL', 'Cold Call'), ('SOCIAL_MEDIA', 'Social Media'), ('DIRECT', 'Direct'), ('OTHER', 'Other')], max_length=20)),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requirement_description', models.TextField(help_text='Description of lead requirement')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('PROPOSAL_SENT', 'Proposal Sent'), ('IN_NEGOTIATION', 'In Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('HOLD', 'Hold'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress from 0-100%')),
                ('expected_closure_date', models.DateField(blank=True, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('next_action_notes', models.TextField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True, help_text='Reason if status is Lost', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='newapp.salesemployee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('originating_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to='newapp.visitlog')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='newapp.prospectcustomer')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='newapp.lead')),
            ],
            options={
                'verbose_name': 'Lead History',
                'verbose_name_plural': 'Lead Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
