# Generated by Django 5.2.7 on 2025-11-04 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_lead_leadhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Site Visit'), ('PROPOSAL', 'Proposal Sent'), ('DEMO', 'Product Demo'), ('NEGOTIATION', 'Negotiation'), ('FOLLOWUP', 'Follow-up'), ('OTHER', 'Other')], max_length=20)),
                ('activity_date', models.DateField(default=django.utils.timezone.now)),
                ('activity_time', models.TimeField(default=django.utils.timezone.now)),
                ('discussion_summary', models.TextField(help_text='Summary of discussion and key points')),
                ('outcome', models.TextField(blank=True, help_text='Outcome of the activity', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('next_followup_date', models.DateField(blank=True, help_text='Date for next follow-up', null=True)),
                ('next_followup_time', models.TimeField(blank=True, help_text='Time for next follow-up', null=True)),
                ('next_action_required', models.TextField(blank=True, help_text='What needs to be done next', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='COMPLETED', max_length=20)),
                ('lead_status_update', models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('PROPOSAL_SENT', 'Proposal Sent'), ('IN_NEGOTIATION', 'In Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('HOLD', 'Hold'), ('CLOSED', 'Closed')], help_text='Updated lead status after this activity', max_length=20, null=True)),
                ('attachment1', models.FileField(blank=True, help_text='Proposal, quote, or other document', null=True, upload_to='activity_attachments/')),
                ('attachment2', models.FileField(blank=True, help_text='Email copy, screenshot, or additional file', null=True, upload_to='activity_attachments/')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='activity_attachments/')),
                ('contact_person', models.CharField(blank=True, help_text='Person contacted', max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='newapp.lead')),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-activity_date', '-activity_time'],
            },
        ),
    ]
