# Generated by Django 5.2.7 on 2025-11-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_salesorder_salesorderactivity_salesorderattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectcustomer',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prospectcustomer',
            name='name',
            field=models.CharField(help_text='Unique customer name', max_length=200, unique=True),
        ),
    ]
