# Generated by Django 5.2.7 on 2025-11-06 06:07

from django.db import migrations


def populate_customer_ids(apps, schema_editor):
    """Populate customer_id for existing customers"""
    ProspectCustomer = apps.get_model('newapp', 'ProspectCustomer')
    
    # Get all customers without customer_id
    customers = ProspectCustomer.objects.filter(customer_id__isnull=True).order_by('id')
    
    for index, customer in enumerate(customers, start=1):
        customer.customer_id = f"CUST-{index:05d}"
        customer.save()


def reverse_populate(apps, schema_editor):
    """Reverse operation - set customer_id to None"""
    ProspectCustomer = apps.get_model('newapp', 'ProspectCustomer')
    ProspectCustomer.objects.all().update(customer_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_prospectcustomer_customer_id_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_customer_ids, reverse_populate),
    ]
