# Generated by Django 5.2.7 on 2025-11-06 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20251106_1137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTermsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('term_name', models.CharField(max_length=200)),
                ('inco_term', models.CharField(blank=True, choices=[('EXW', 'Ex Works'), ('FCA', 'Free Carrier'), ('CPT', 'Carriage Paid To'), ('CIP', 'Carriage and Insurance Paid To'), ('DAP', 'Delivered at Place'), ('DPU', 'Delivered at Place Unloaded'), ('DDP', 'Delivered Duty Paid'), ('FAS', 'Free Alongside Ship'), ('FOB', 'Free on Board'), ('CFR', 'Cost and Freight'), ('CIF', 'Cost, Insurance and Freight')], max_length=10, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Terms',
                'verbose_name_plural': 'Delivery Terms',
                'ordering': ['term_code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTermsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('term_name', models.CharField(max_length=200)),
                ('days', models.IntegerField(help_text='Number of days for payment')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Terms',
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['term_code'],
            },
        ),
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tax_name', models.CharField(max_length=200)),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST'), ('CGST', 'CGST'), ('SGST', 'SGST'), ('CESS', 'CESS'), ('OTHER', 'Other')], max_length=20)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Master',
                'verbose_name_plural': 'Tax Masters',
                'ordering': ['tax_code'],
            },
        ),
        migrations.CreateModel(
            name='VisitPurposeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('purpose_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visit Purpose',
                'verbose_name_plural': 'Visit Purposes',
                'ordering': ['purpose_code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('SALES_ORDER', 'Sales Order'), ('DISCOUNT', 'Discount Approval')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Use 999999999 for unlimited', max_digits=15)),
                ('approver_role', models.CharField(help_text='Role required for approval (e.g., Sales Manager, Director)', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Specific approver (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_matrix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Matrix',
                'verbose_name_plural': 'Approval Matrices',
                'ordering': ['document_type', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('CONSUMABLE', 'Consumable')], default='PRODUCT', max_length=20)),
                ('unit_of_measurement', models.CharField(default='PCS', help_text='e.g., PCS, KG, LTR, MTR', max_length=20)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum selling price', max_digits=15)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, help_text='HSN/SAC code for GST', max_length=20, null=True)),
                ('default_tax_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Default GST %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Masters',
                'ordering': ['item_code'],
            },
        ),
    ]
