# Generated by Django 5.2.7 on 2025-11-06 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_deliverytermsmaster_paymenttermsmaster_taxmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_terms_master',
            field=models.ForeignKey(blank=True, help_text='Select from Delivery Terms Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='newapp.deliverytermsmaster'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms_master',
            field=models.ForeignKey(blank=True, help_text='Select from Payment Terms Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='newapp.paymenttermsmaster'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_master',
            field=models.ForeignKey(blank=True, help_text='Select from Item Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='newapp.itemmaster'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_terms_master',
            field=models.ForeignKey(blank=True, help_text='Select from Delivery Terms Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='newapp.deliverytermsmaster'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_terms_master',
            field=models.ForeignKey(blank=True, help_text='Select from Payment Terms Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='newapp.paymenttermsmaster'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='item_master',
            field=models.ForeignKey(blank=True, help_text='Select from Item Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='newapp.itemmaster'),
        ),
    ]
