# Generated by Django 5.2.7 on 2025-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_servicecall_servicecallattachment_servicecallitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecallitem',
            name='warranty_applicable',
        ),
        migrations.AddField(
            model_name='servicecallitem',
            name='batch_no',
            field=models.CharField(blank=True, help_text='Batch number for traceability', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecallitem',
            name='fault_found',
            field=models.TextField(blank=True, help_text='Description of fault found in this item', null=True),
        ),
        migrations.AddField(
            model_name='servicecallitem',
            name='labour_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Labour hours for this item', max_digits=6),
        ),
        migrations.AddField(
            model_name='servicecallitem',
            name='labour_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Labour rate per hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicecallitem',
            name='product_serial_no',
            field=models.CharField(blank=True, help_text="Product's serial number if fielded", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecallitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price', max_digits=12),
        ),
        migrations.AddField(
            model_name='servicecallitem',
            name='warranty_covered',
            field=models.BooleanField(default=False, help_text='Covered under warranty (Y/N)'),
        ),
        migrations.AlterField(
            model_name='servicecallitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total including parts, labour, and tax', max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicecallitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity of spare parts used', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicecallitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number for traceability', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicecallitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price', max_digits=12),
        ),
    ]
