# Generated by Django 5.2.7 on 2025-12-02 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_remove_servicecallitem_warranty_applicable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_types', models.CharField(blank=True, help_text='Comma-separated applicable service types', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fault Category',
                'verbose_name_plural': 'Fault Categories',
                'ordering': ['category_code'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('BREAKDOWN', 'Breakdown'), ('PREVENTIVE', 'Preventive Maintenance'), ('INSTALLATION', 'Installation'), ('CALIBRATION', 'Calibration'), ('WARRANTY', 'Warranty Claim'), ('AMC', 'AMC Service'), ('ALL', 'All Service Types')], default='ALL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('ALL', 'All Priorities')], default='ALL', max_length=20)),
                ('response_time_sla_hours', models.IntegerField(default=24, help_text='Response time in hours')),
                ('resolution_time_sla_hours', models.IntegerField(default=72, help_text='Resolution time in hours')),
                ('business_hours_only', models.BooleanField(default=True)),
                ('escalation_threshold_percentage', models.IntegerField(default=80, help_text='Percentage of SLA time for escalation warning')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA Configuration',
                'verbose_name_plural': 'SLA Configurations',
                'ordering': ['service_type', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_invoice_id', models.CharField(max_length=50, unique=True)),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_parts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_labour', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_travel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PART_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Transfer'), ('CARD', 'Card Payment'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('linked_accounting_doc', models.CharField(blank=True, help_text='Reference to SAP B1 or finance system', max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('service_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice', to='newapp.servicecall')),
            ],
            options={
                'verbose_name': 'Service Invoice',
                'verbose_name_plural': 'Service Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='SpareUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_used', models.DecimalField(decimal_places=2, help_text='Quantity of spare parts used', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=12)),
                ('warehouse_id', models.CharField(blank=True, help_text='Source warehouse/store', max_length=50, null=True)),
                ('replacement_reason', models.CharField(choices=[('WARRANTY', 'Warranty Replacement'), ('WEAR_AND_TEAR', 'Wear and Tear'), ('DAMAGE', 'Damage/Malfunction'), ('UPGRADE', 'Upgrade/Improvement'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('technician_remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_usage_records', to='newapp.itemmaster')),
                ('service_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_usage', to='newapp.servicecall')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Inventory manager verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_spare_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spare Parts Usage',
                'verbose_name_plural': 'Spare Parts Usage Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('symptom_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fault_categories', models.ManyToManyField(blank=True, related_name='symptoms', to='newapp.faultcategory')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['symptom_code'],
            },
        ),
    ]
