# Generated by Django 5.2.7 on 2025-12-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_faultcategory_slaconfig_serviceinvoice_spareusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecall',
            name='equipment_details',
            field=models.TextField(blank=True, help_text='Make/model/serial information for the equipment', null=True),
        ),
    ]
