# Generated by Django 5.2.7 on 2025-12-10 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_servicecall_equipment_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ['employee_code'], 'verbose_name': 'Technician', 'verbose_name_plural': 'Technicians'},
        ),
        migrations.AddField(
            model_name='technician',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='newapp.department'),
        ),
        migrations.AddField(
            model_name='technician',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='newapp.designation'),
        ),
        migrations.AddField(
            model_name='technician',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Currently available for service calls'),
        ),
        migrations.AddField(
            model_name='technician',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when technician joined'),
        ),
        migrations.AddField(
            model_name='technician',
            name='license_number',
            field=models.CharField(blank=True, help_text='Driving license or professional license', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or remarks', null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='reporting_to',
            field=models.ForeignKey(blank=True, help_text='Senior technician/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='newapp.technician'),
        ),
        migrations.AddField(
            model_name='technician',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='newapp.territory'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_code',
            field=models.CharField(db_index=True, help_text='Unique technician employee code (e.g., TECH-00001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='specialization',
            field=models.CharField(blank=True, help_text='E.g., Pumps, Motors, HVAC, Electronics, Automation', max_length=200, null=True),
        ),
    ]
