# Generated by Django 5.2.7 on 2025-12-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_alter_technician_options_technician_aadhar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
