# Generated by Django 5.2.7 on 2025-12-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='servicecall',
            options={},
        ),
        migrations.AddField(
            model_name='servicecall',
            name='item_name',
            field=models.CharField(blank=True, help_text='Equipment / Item name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicecall',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Equipment serial number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicecall',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='warrantyrecord',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CLAIMED', 'Claimed'), ('VOID', 'Void')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='warrantyrecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
