# Generated by Django 5.2.7 on 2025-12-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0018_delete_customer_alter_servicecall_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospectcustomer",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicecall",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("BREAKDOWN", "Breakdown"),
                    ("SERVICE", "Service"),
                    ("INSTALLATION", "Installation"),
                ],
                default="SERVICE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servicecall",
            name="origin",
            field=models.CharField(
                choices=[
                    ("PHONE", "Phone"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("PORTAL", "Customer Portal"),
                    ("VISIT", "Site Visit"),
                ],
                default="PHONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servicecall",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("MECHANICAL", "Mechanical"),
                    ("ELECTRICAL", "Electrical"),
                    ("SOFTWARE", "Software"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prospectcustomer",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="servicecall",
            name="contact_person",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="servicecall",
            name="contact_phone",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="servicecall",
            name="item_name",
            field=models.CharField(
                blank=True, help_text="Equipment / Item name", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicecall",
            name="service_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
